--- !ditz.rubyforge.org,2008-03-06/project 
name: HGDP database
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: HGDP database
- !ditz.rubyforge.org,2008-03-06/component 
  name: database schema
- !ditz.rubyforge.org,2008-03-06/component 
  name: database setup
- !ditz.rubyforge.org,2008-03-06/component 
  name: hgdp files parsing
- !ditz.rubyforge.org,2008-03-06/component 
  name: query scripts
- !ditz.rubyforge.org,2008-03-06/component 
  name: to discuss
releases: []

